---
title: "Aug23_SimpleIndex_Analysis"
author: "Franky Zhang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
library(openxlsx)
library(RColorBrewer)

source('../Background/functions_0706.R')
source('../Code/functions_franky_0725.R')
source('../Background/growth_rate_function_original.R')

generate_growth_rate_list <- function(df) {
  
  # Function to process growth rates for a given column
  process_growth_rates <- function(data, column_name) {
    output_ <- extract_growth_rates(data[[column_name]], data$date, dow = "none", denominator = 3)
    list(
      fit = output_$model_fit %>% 
        dplyr::select(Date_numeric, date, full_fit) %>% 
        dplyr::rename(!!paste0(column_name, "_fit") := full_fit),
      gr_fit = output_$fitted_rates %>% 
        dplyr::select(Date_numeric, date, rate) %>% 
        dplyr::rename(!!paste0(column_name, "_gr_fit") := rate)
    )
  }
  
  # Initialize the output list
  list_ <- list()
  
  # Loop over each variant and process data
  for (variant_ in unique(df$classified_label)) {
    
    cat("processing-", variant_, "\n")
    
    variant_df_ <- df %>% 
      dplyr::filter(classified_label == variant_)
    
    # Process 'numerator' and 'sharing' columns
    abs_data <- process_growth_rates(variant_df_, "numerator")
    share_data <- process_growth_rates(variant_df_, "sharing")
    
    # Combine the results
    output_ <- abs_data$fit %>% 
      dplyr::left_join(abs_data$gr_fit, by = c("Date_numeric", "date")) %>% 
      dplyr::left_join(share_data$fit, by = c("Date_numeric", "date")) %>% 
      dplyr::left_join(share_data$gr_fit, by = c("Date_numeric", "date"))
    
    # Store the raw data and the fitted output in the list
    list_[[variant_]] <- list(
      raw = variant_df_,
      fit = output_
    )
  }
  
  # Return the final list
  return(list_)
}

rates_generating <- function(df, Days){
  
  df_30_ <- df %>% 
  dplyr::filter(
    gap <= Days
  ) %>% 
  dplyr::group_by(
    classified_label
  ) %>%
  dplyr::filter(
    sum(sharing == 0) <= (Days*0.9) # at least 10% non-zero data
  ) %>%
  dplyr::ungroup()
  
  return(generate_growth_rate_list(df_30_))
  
}

correlation_pvalues_calculate <- function(df, response, start, end, step_size = 1){
  
  # start = 30; end = 40; step_size = 2; df = Korea_data; response = Korea_dominance # test inputs
  
  type_ <- c("mean_raw_abs", "mean_raw_share", "mean_fit_abs", "mean_fit_abs_gr", "mean_fit_share", "mean_fit_share_gr", 
               "max_raw_abs", "max_raw_share", "max_fit_abs", "max_fit_abs_gr", "max_fit_share", "max_fit_share_gr")
  
  corr_df <- data.frame(Type = type_)
  p_value_df <- data.frame(Type = type_)
  
  for (d in seq(from = start, to = end, by = step_size)) {
    
    # d = 30 # test input 
    
    cat("Day-", d, "\n")
    
    list_ <- rates_generating(df, Days = d)
    
    dominance_ <- response %>% 
      dplyr::filter(
        classified_label %in% names(list_)
      ) %>% 
      dplyr::mutate(
        classified_label = factor(classified_label, levels = names(list_))
      ) %>% 
      dplyr::arrange(
        classified_label
      )
    
    # all(dominance_$classified_label == names(list_)) # check the order
    
    mean_raw_abs <- c()
    mean_raw_share <- c()
    mean_fit_abs <- c()
    mean_fit_abs_gr <- c()
    mean_fit_share <- c()
    mean_fit_share_gr <- c()
    
    max_raw_abs <- c()
    max_raw_share <- c()
    max_fit_abs <- c()
    max_fit_abs_gr <- c()
    max_fit_share <- c()
    max_fit_share_gr <- c()
    
    for (i in 1:length(names(list_))) {
      
      # i = 10 # test input
      
      name = names(list_)[i]
      
      raw_ <- list_[[name]]$raw
      fit_ <- list_[[name]]$fit
      
      mean_raw_abs[i] <- mean(raw_$numerator)
      mean_raw_share[i] <- mean(raw_$sharing)
      mean_fit_abs[i] <- mean(fit_$numerator_fit)
      mean_fit_abs_gr[i] <- mean(fit_$numerator_gr_fit)
      mean_fit_share[i] <- mean(fit_$sharing_fit)
      mean_fit_share_gr[i] <- mean(fit_$sharing_gr_fit)
      
      max_raw_abs[i] <- max(raw_$numerator)
      max_raw_share[i] <- max(raw_$sharing)
      max_fit_abs[i] <- max(fit_$numerator_fit)
      max_fit_abs_gr[i] <- max(fit_$numerator_gr_fit)
      max_fit_share[i] <- max(fit_$sharing_fit)
      max_fit_share_gr[i] <- max(fit_$sharing_gr_fit)
      
    }
    
    cal_list_ <- list(mean_raw_abs, mean_raw_share, mean_fit_abs, mean_fit_abs_gr, mean_fit_share, mean_fit_share_gr, 
                      max_raw_abs, max_raw_share, max_fit_abs, max_fit_abs_gr, max_fit_share, max_fit_share_gr)
    
    names(cal_list_) <- type_
    
    cor_ <- c()
    
    p_values <- c()
    
    for (j in 1:length(type_)) {
      
      # j = 1 # test input 
      
      type <- type_[j]
      
      cor_[j] <- cor.test(cal_list_[[type]], dominance_$dominance)$estimate
      
      p_values[j] <- cor.test(cal_list_[[type]], dominance_$dominance)$p.value
      
    } 
    
    corr_df <- cbind(corr_df, cor_)
    p_value_df <- cbind(p_value_df, p_values)
    
  }
    
  colnames(corr_df) <- c("Type", paste0(seq(from = start, to = end, by = step_size), "_days"))
  colnames(p_value_df) <- c("Type", paste0(seq(from = start, to = end, by = step_size), "_days"))
  
  return(list(corr = corr_df, p.value = p_value_df))
}
```

## Data Processing

```{r}
# get the alias
alias_list <- get_alias()

# set the time range (as large as possible)
months_from_most_recent <- 365 * 6

# load the data and process 
url <- '../Data/summary_gisaid_new.csv'
data <- readr::read_csv(url) |>
  dplyr::filter(
    # country == country_select,
    lineage != 'Unassigned',
    date >= max(date, na.rm = T) - months_from_most_recent
  ) |>
  dplyr::mutate(
    alias = gsub(
      pattern = "[^a-zA-Z]",
      replacement = "",
      x = lineage
    ),
    second_part = gsub(pattern = "[a-zA-Z]",
                       replacement = "",
                       x = lineage)
  ) |>
  dplyr::left_join(alias_list) |>
  dplyr::mutate(
    unaliased_lineage  =
      dplyr::if_else(!is.na(alias_lineage),
                     paste0(alias_lineage, second_part),
                     lineage),
  )

dataset <- data %>%
  dplyr::select(country, date, lineage, numerator, unaliased_lineage) %>%
  dplyr::rename(n = numerator)

# # classified the variants
# summarised <- dataset %>%
#   dplyr::group_by(country, unaliased_lineage) %>%
#   dplyr::summarise(n = sum(n))
# 
# # set p limit
# p_lim <- 0.01
# 
# # set n limit
# n_lim <- 100
# 
# # get the classification to append
# # save the result since the function costs a lot of time
# classification_to_append <- get_classification(
#   lineages = summarised$unaliased_lineage,
#   number_sequences = summarised$n,
#   p_lim = p_lim, n_lim = n_lim, alias_list
# ) |>
#   dplyr::mutate(
#     decimal_lineage = paste0(classified_unasliased, '.')
#   )
# 
# saveRDS(classification_to_append, "Data/Aug15_classification_to_append_Combined.rds")

# load the .rds file
append_url <- "../Data/Aug06_classification_to_append_Combined.rds"
classification_to_append <- readRDS(append_url)

# append the classification
classified_data <- dataset |>
  dplyr::mutate(
    decimal_lineage = paste0(unaliased_lineage, '.')
  ) |>
  fuzzyjoin::fuzzy_left_join(
    classification_to_append,
    by = 'decimal_lineage',
    match_fun = stringr::str_starts
  ) |>
  dplyr::filter(
    is.na(classified_unasliased) | stringr::str_length(classified_unasliased) == max(stringr::str_length(classified_unasliased)),
    .by = c(lineage, date)
  ) |>
  dplyr::mutate(
    length_class = stringr::str_count(classified_unasliased, '\\.'),
    length_lineage = stringr::str_count(unaliased_lineage, '\\.'),
    classified_label = dplyr::if_else((length_lineage - length_class) <= 1,
                                      classified_label,
                                      NA),
    classified_label = dplyr::if_else(is.na(classified_label),
                                      "Other",
                                      classified_label)
  ) |>
  dplyr::filter(classified_label != 'Other') |>
  dplyr::select(country, date, lineage, n, classified_label)

# check the number of the classified labels
# length(unique(classified_data$lineage)) # 1608
# length(unique(classified_data$classified_label)) # 88

classified_data <- classified_data %>% 
  dplyr::select(
    country, date, n, classified_label
  ) %>% 
  dplyr::group_by(
    country, classified_label, date, 
  ) %>% 
  dplyr::summarise(
    n_total = sum (n)
  )

# complete the dates to be continuous
complete_dates <- function(data) {
  data %>%
    dplyr::group_by(
      country, 
      classified_label
    ) %>%
    tidyr::complete(date = seq.Date(min(date), max(date), by = "day")
    ) %>%
    tidyr::replace_na(
      list(n_total = 0)
    ) %>%
    dplyr::ungroup()
}

classified_data <- complete_dates(classified_data) %>% 
  dplyr::rename(
    numerator = n_total
  ) %>% 
  dplyr::group_by(
    country, date
  ) %>% 
  dplyr::mutate(
    denominator = sum(numerator, na.rm = TRUE)
  ) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(
    share = numerator/denominator
  )

# separate data
Korea_data <- classified_data %>%
  dplyr::filter(
    country == "South Korea"
  ) %>%
  dplyr::arrange(
    classified_label, date
  ) %>%
  dplyr::group_by(
    classified_label
  ) %>%
  dplyr::filter(
    dplyr::n() >= 60
  ) %>%
  dplyr::mutate(
    sharing = dplyr::coalesce(share, 0),
    gap = as.numeric(date - dplyr::first(date))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(-share)

Korea_dominance <- Korea_data %>% 
  dplyr::group_by(
    classified_label
  ) %>% 
  dplyr::summarise(
    dominance = sum(sharing, na.rm = TRUE),
  ) %>% 
  dplyr::arrange(
    desc(dominance)
  )

UK_data <- classified_data %>%
  dplyr::filter(
    country == "United Kingdom"
  ) %>%
  dplyr::arrange(
    classified_label, date
  ) %>%
  dplyr::group_by(
    classified_label
  ) %>%
  dplyr::filter(
    dplyr::n() >= 60
  ) %>%
  dplyr::mutate(
    sharing = dplyr::coalesce(share, 0),
    gap = as.numeric(date - dplyr::first(date))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(-share)

UK_dominance <- UK_data %>% 
  dplyr::group_by(
    classified_label
  ) %>% 
  dplyr::summarise(
    dominance = sum(sharing, na.rm = TRUE),
  ) %>% 
  dplyr::arrange(
    desc(dominance)
  )

rm(alias_list, classified_data, data, append_url, url)
```

## Calculate correlations (mean/max absoluate or rates)

```{r}
# apply the defined functions
# Korea_result <- correlation_pvalues_calculate(Korea_data, Korea_dominance, 15, 60, 1)
# UK_result <- correlation_pvalues_calculate(UK_data, UK_dominance, 15, 60, 1)

Korea_result_show <- correlation_pvalues_calculate(Korea_data, Korea_dominance, 30, 60, 5)
UK_result_show <- correlation_pvalues_calculate(UK_data, UK_dominance, 30, 60, 5)
# 
# write.xlsx(Korea_result_show, file = "../Data/Korea_result_show_Aug24.xlsx")
# write.xlsx(UK_result_show, file = "../Data/UK_result_show_Aug24.xlsx")
```

## Visualize the results

```{r}
Korea_long <- Korea_result$corr %>%
  pivot_longer(cols = starts_with("30_days"):starts_with("60_days"),
               names_to = "Day",
               names_prefix = "days_",
               values_to = "Value") %>%
  mutate(Day = as.numeric(substr(Day, 1, 2)), 
         Country = "South Korea")

UK_long <- UK_result$corr %>%
  pivot_longer(cols = starts_with("30_days"):starts_with("60_days"),
               names_to = "Day",
               names_prefix = "days_",
               values_to = "Value") %>%
  mutate(Day = as.numeric(substr(Day, 1, 2)), 
         Country = "United Kingdom")

plot_data <- rbind(Korea_long, UK_long)

plot_data$Type <- factor(plot_data$Type, 
                            levels = c("mean_raw_abs", "mean_raw_share", "mean_fit_abs", 
                                       "mean_fit_abs_gr", "mean_fit_share", "mean_fit_share_gr", 
                                       "max_raw_abs", "max_raw_share", "max_fit_abs", 
                                       "max_fit_abs_gr", "max_fit_share", "max_fit_share_gr"))

ggplot(plot_data, aes(x = Day, y = Value, color = Type, group = Type)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  labs(title = "Correlation Over Time by Country",
       x = "Days to Use",
       y = "Pearson Correlation") +
  facet_wrap(~ Country) +
  scale_color_brewer(palette = "Paired") +  # Use the Paired palette for 12 colors
  theme_bw()
```


## Re-do it by variants

```{r}
matching_list <- data.frame(
  PANGO_Lineage = c("Alpha", "Beta", "Gamma", "Delta", "Omicron"), 
  Alias = c("B.1.1.7", "B.1.351", "P.1", "B.1.617.2", "B.1.1.529")
)


Korea_data %>% 
  dplyr::mutate(
    alias = ifelse(grepl("B.1.1.7", classified_label), "Alpha", 
                   ifelse(grepl("B.1.351", classified_label), "Beta", 
                          ifelse(grepl("P.1", classified_label), "Gamma", 
                                 ifelse(grepl("B.1.617.2", classified_label), "Delta", 
                                        ifelse(grepl("B.1.1.529", classified_label), "Omicron", NA)))))) -> Korea_data
  
UK_data %>% 
  dplyr::mutate(
    alias = ifelse(grepl("B.1.1.7", classified_label), "Alpha", 
                   ifelse(grepl("B.1.351", classified_label), "Beta", 
                          ifelse(grepl("P.1", classified_label), "Gamma", 
                                 ifelse(grepl("B.1.617.2", classified_label), "Delta", 
                                        ifelse(grepl("B.1.1.529", classified_label), "Omicron", NA)))))) -> UK_data
table(UK_data$alias)
table(Korea_data$alias)





# Korea_Alpha_show <- correlation_pvalues_calculate((Korea_data %>% dplyr::filter(alias == "Alpha")), Korea_dominance, 30, 60, 5)
# UK_Alpha_show <-    correlation_pvalues_calculate(UK_data %>% dplyr::filter(alias == "Alpha"), UK_dominance, 30, 60, 5)

Korea_Delta_show <- correlation_pvalues_calculate(Korea_data %>% dplyr::filter(alias == "Delta"), Korea_dominance, 30, 60, 5)
UK_Delta_show <-    correlation_pvalues_calculate(UK_data %>% dplyr::filter(alias == "Delta"), UK_dominance, 30, 60, 5)



```










